project_id = "vxrsqftlaguiwprcqlbw"

[functions.cleanup-old-storage]
verify_jwt = false

[functions.rate-limiter]
verify_jwt = false

[functions.help-chat]
verify_jwt = false

[functions.analyze-message]
verify_jwt = false

[functions.generate-story-image]
verify_jwt = false

[functions.send-otp-sms]
verify_jwt = false

[functions.create-paypal-order]
verify_jwt = false

[functions.capture-paypal-order]
verify_jwt = false